spring:
  #DataSource
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydb}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:C0nnect123}
    driver-class-name: org.postgresql.Driver

  #JPA
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #RabbitMQ
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  #Redis
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  #DevTools
  devtools:
    restart:
      enabled: true

#Security
security:
  jwt:
      # Use a secret with at least 32 characters to satisfy HS256 key length
    secret: "nahXkTgSwp4QzcZK13495vff5mYaZBFppzhfeBXfr6i"
    # 1 day in milliseconds
    expirationMillis: 86400000

#App - Custom
app:
  #RabbitMQ
  rabbit:
    product:
      exchange: ${RABBITMQ_PRODUCT_EXCHANGE:product.exchange}
      queue: ${RABBITMQ_PRODUCT_QUEUE:product.queue}
      routing-key: ${RABBITMQ_PRODUCT_CREATED:product.created}